SQL_DDL_HW
Volod980/Volodymyr_Kotelnytskyi_AU24 pull request #5
Opened 2024-11-10 16:32 UTC by Volod980

2024-11-18 17:24 UTC, albusel requested changes
Hi Volodymyr,

Current state wouldn't be allowed to deploy on production for the following reasons.

Script isn't rerunnable.

No 'IF NOT EXISTS' used for tables creation

Primary keys are hardcoded

No checks if a value already exists 

Hardcode is used everywhere, instead of "INSERT INTO ... SELECT" "INSERT INTO ... VALUES" is used

No comments at all

It would be great to fix the point above, thanks

2024-11-20 20:54 UTC, Volod980 commented
Hello, I  put updated file "SQL_DDL_Volodymyr_Kotelnytskyi_HW_UPD". Thank you so much!

2024-11-28 19:57 UTC, albusel commented on SQL_DDL_Volodymyr_Kotelnytskyi_HW_UPD.sql
> +select 'Vokzalna' as name, true as is_transfer, 1 as line_id
Hardcoded line_id
Select statement should be used to find line_id

2024-11-28 19:57 UTC, albusel commented on SQL_DDL_Volodymyr_Kotelnytskyi_HW_UPD.sql
> +                  and s.position_id = position_id
Hardcode

2024-11-28 19:58 UTC, albusel requested changes
Hardcode is still in place, let's get rid of it!

2024-11-28 20:00 UTC, albusel commented
and please add LOWER/UPPER function for strings

2024-11-29 21:53 UTC, Volod980 commented
Hello, thank you very much for comments. I changed file SQL_DDL_Volodymyr_Kotelnytskyi_HW_UPD

2024-12-09 16:28 UTC, albusel approved these changes
Approved, you can merge

2024-12-11 16:19 UTC, merged